version: "3"

services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: otel-jaeger
    # restart: always
    networks: [opentel]
    ports:
    - "16686:16686" # web
    - "14268"       #
    - "14250"       # expose to otel-collector

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    restart: always
    depends_on: [jaeger-all-in-one]
    volumes:
    - ./otel-collector_config.yaml:/etc/otel-collector_config.yaml
    networks: [opentel]
    ports:
    - "1888:1888"   # pprof extension
    - "8888:8888"   # Prometheus metrics exposed by the collector
    - "8889:8889"   # Prometheus exporter metrics
    - "13133:13133" # health_check extension
    - "4317:4317"   # OTLP gRPC receiver
    - "55670:55679" # zpages extension
    command: ["--config=/etc/otel-collector_config.yaml"]

  prometheus:
    image: prom/prometheus:main
    container_name: otel-prometheus
    restart: always
    volumes:
    - ./prometheus_config.yaml:/etc/prometheus/prometheus_config.yaml
    - ./prometheus_web.yaml:/etc/prometheus/prometheus_web.yaml
    - prometheus:/prometheus/data
    networks: [opentel]
    ports: ["9090:9090"]
    command:
    - '--config.file=/etc/prometheus/prometheus_config.yaml'
    - '--web.config.file=/etc/prometheus/prometheus_web.yaml'
    # - '--config.file=/etc/prometheus/prometheus.yaml'
    # - '--storage.tsdb.path=/prometheus/data'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'

volumes:
  # opentel_prometheus
  prometheus:

networks:
  opentel:
    name: opentel
    driver: bridge
    external: false
