version: '3'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always

    # network_mode: bridge
    networks: ["postgres"]
    ports: ["127.0.0.1:5432:5432"]

    volumes:
    - ./data:/var/lib/postgresql/data
    # - postgres_data:/var/lib/postgresql/data
    # - ./postgresql.conf:/var/lib/postgresql/data/pgdata/postgresql.conf
    # - ./log:/var/log/postgresql/

    environment:
    - TZ=Asia/Shanghai
    - PGTZ=Asia/Shanghai
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

# volums:
#    postgres_data:

networks:
  postgres: { name: "postgres", driver: "bridge", external: false }
